# Generated by Django 3.1.7 on 2021-05-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('repo_id', models.IntegerField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('repo_name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=255)),
                ('created_date', models.DateField()),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
    ]
