version: "3.8"
services:

    # Redis
    redis:
        container_name: redis2
        image: redis:alpine

    # Database postgres
    db:
        container_name: postgres_db
        image: postgres
        volumes: 
            - ./data/db:/var/lib/postgresql/data
        environment: 
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        
    # Django application
    app:
        container_name: core
        build: .
        volumes: 
            - .:/app
        ports:
            - 8000:8000
        image: app:django
        command: python manage.py runserver 0.0.0.0:8000
        depends_on: 
            - db

    flower:
        container_name: flower
        image: mher/flower:0.9.7
        command: flower --broker=redis://redis:6379 --port=5555
        ports: 
            - 5557:5555
        depends_on: 
            - redis
    
    celery:
        container_name: celery2
        restart: always
        build: 
            # where is dockerfile located
            context: .
        # in production use [celery -A core worker]
        command: celery -A core worker -l INFO
        volumes: 
            - .:/app
        depends_on: 
            - db
            - redis
            - app

    celery-beat:
        container_name: celery2_eat
        build:
            context: .
        command: celery -A core beat -l INFO
        volumes: 
            - .:/app
        depends_on: 
            - redis